# Copyright © 2025 Cassidy Spring (Bee).
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Swiftly Swift
author: Cassidy Spring (Bee)
description: Installs Swiftly and a Swift Toolchain.
branding:
  icon: command
  color: orange

inputs:
  swift-version:
    description: Swift Toolchain version that Swiftly will install and use, defaults to latest.
    required: true
    default: latest
  swiftly-cache:
    description: Whether to cache the swiftly installation. Set to false to force a fresh download.
    required: false
    default: "true"

outputs:
  swift-version:
    description: The resolved Swift version that was installed.
    value: ${{ steps.resolve-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'macOS' && runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error::Only supports macOS and linux"
        exit 1

    # Swiftly Caching - cache the installed swiftly, use self-update to keep current
    - name: Restore Swiftly - macOS
      if: ${{ runner.os == 'macOS' && inputs.swiftly-cache == 'true' }}
      uses: actions/cache/restore@v4
      id: restore-swiftly-cache-macos
      with:
        path: ~/.swiftly
        key: swiftly-${{ runner.os }}-${{ runner.arch }}

    - name: Restore Swiftly - Linux
      if: ${{ runner.os == 'Linux' && inputs.swiftly-cache == 'true' }}
      uses: actions/cache/restore@v4
      id: restore-swiftly-cache-linux
      with:
        path: ~/.local/share/swiftly
        key: swiftly-${{ runner.os }}-${{ runner.arch }}

    - name: Install Swiftly - macOS
      if: ${{ runner.os == 'macOS' && steps.restore-swiftly-cache-macos.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
        pkgutil --check-signature swiftly.pkg
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        ~/.swiftly/bin/swiftly init --verbose --assume-yes --skip-install
        rm -f swiftly.pkg

    - name: Install Swiftly - Linux
      if: ${{ runner.os == 'Linux' && steps.restore-swiftly-cache-linux.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl -o swiftly.tar.gz https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz
        tar -zxf swiftly.tar.gz
        ./swiftly init --verbose --assume-yes --skip-install
        rm -f swiftly swiftly.tar.gz

    - name: Cache Swiftly - macOS
      if: ${{ runner.os == 'macOS' && inputs.swiftly-cache == 'true' && steps.restore-swiftly-cache-macos.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.swiftly
        key: swiftly-${{ runner.os }}-${{ runner.arch }}

    - name: Cache Swiftly - Linux
      if: ${{ runner.os == 'Linux' && inputs.swiftly-cache == 'true' && steps.restore-swiftly-cache-linux.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.local/share/swiftly
        key: swiftly-${{ runner.os }}-${{ runner.arch }}

    - name: Activate Swiftly - macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        . "${SWIFTLY_HOME_DIR:-$HOME/.swiftly}/env.sh"
        if ! swiftly self-update --assume-yes; then
          echo "::warning::Failed to update swiftly, continuing with cached version"
        fi
        hash -r
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Activate Swiftly - Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"
        if ! swiftly self-update --assume-yes; then
          echo "::warning::Failed to update swiftly, continuing with cached version"
        fi
        hash -r
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Resolve Swift Version
      id: resolve-version
      shell: bash
      run: |
        INPUT_VERSION="${{ inputs.swift-version }}"
        TOOLCHAINS=$(swiftly list-available --format json)

        if [ "$INPUT_VERSION" = "latest" ]; then
          # Latest stable release
          RESOLVED=$(echo "$TOOLCHAINS" | jq -r '.toolchains[0].version.name')
        elif [[ "$INPUT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          # Exact version (e.g., 6.2.1) - use as-is
          RESOLVED="$INPUT_VERSION"
        elif [[ "$INPUT_VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
          # Minor version (e.g., 6.2) - find latest patch
          MAJOR=$(echo "$INPUT_VERSION" | cut -d. -f1)
          MINOR=$(echo "$INPUT_VERSION" | cut -d. -f2)
          RESOLVED=$(echo "$TOOLCHAINS" | jq -r --arg maj "$MAJOR" --arg min "$MINOR" \
            '.toolchains | map(select(.version.major == ($maj | tonumber) and .version.minor == ($min | tonumber))) | .[0].version.name')
        elif [[ "$INPUT_VERSION" =~ ^[0-9]+$ ]]; then
          # Major version (e.g., 6) - find latest minor.patch
          RESOLVED=$(echo "$TOOLCHAINS" | jq -r --arg maj "$INPUT_VERSION" \
            '.toolchains | map(select(.version.major == ($maj | tonumber))) | .[0].version.name')
        else
          # Snapshot or other format - use as-is
          RESOLVED="$INPUT_VERSION"
        fi

        echo "Resolved '$INPUT_VERSION' to: $RESOLVED"
        echo "version=$RESOLVED" >> $GITHUB_OUTPUT

    # Toolchain Caching
    - name: Restore Swift Toolchain - macOS
      if: ${{ runner.os == 'macOS' }}
      uses: actions/cache/restore@v4
      id: restore-toolchain-cache-macos
      with:
        path: ~/Library/Developer/Toolchains
        key: swift-toolchain-${{ runner.os }}-${{ runner.arch }}-${{ steps.resolve-version.outputs.version }}

    - name: Restore Swift Toolchain - Linux
      if: ${{ runner.os == 'Linux' }}
      uses: actions/cache/restore@v4
      id: restore-toolchain-cache-linux
      with:
        path: ~/.local/share/swiftly/toolchains
        key: swift-toolchain-${{ runner.os }}-${{ runner.arch }}-${{ steps.resolve-version.outputs.version }}

    # NOTE: It feels bad to have sudo statements here but I could not get the post install to work
    # without both of them in place on linux. Neither (and chmod at all) is required on macOS.
    # So this would be nice to dig into more but definitely done for now.
    - name: Install Swift Toolchain
      if: ${{ (runner.os == 'macOS' && steps.restore-toolchain-cache-macos.outputs.cache-hit != 'true') || (runner.os == 'Linux' && steps.restore-toolchain-cache-linux.outputs.cache-hit != 'true') }}
      shell: bash
      run: |
        swiftly install --use ${{ steps.resolve-version.outputs.version }} --post-install-file=post-install.sh
        if [ -f post-install.sh ]; then
          sudo chmod u+x post-install.sh
          sudo ./post-install.sh
        fi

    - name: Cache Swift Toolchain - macOS
      if: ${{ runner.os == 'macOS' && steps.restore-toolchain-cache-macos.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/Library/Developer/Toolchains
        key: swift-toolchain-${{ runner.os }}-${{ runner.arch }}-${{ steps.resolve-version.outputs.version }}

    - name: Cache Swift Toolchain - Linux
      if: ${{ runner.os == 'Linux' && steps.restore-toolchain-cache-linux.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.local/share/swiftly/toolchains
        key: swift-toolchain-${{ runner.os }}-${{ runner.arch }}-${{ steps.resolve-version.outputs.version }}

    - name: Activate Cached Toolchain - Linux
      if: ${{ runner.os == 'Linux' && steps.restore-toolchain-cache-linux.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        TOOLCHAIN_PATH="$HOME/.local/share/swiftly/toolchains/${{ steps.resolve-version.outputs.version }}/usr/bin"
        echo "Adding cached toolchain to PATH: $TOOLCHAIN_PATH"
        echo "$TOOLCHAIN_PATH" >> $GITHUB_PATH

    - name: Activate Cached Toolchain - macOS
      if: ${{ runner.os == 'macOS' && steps.restore-toolchain-cache-macos.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        TOOLCHAIN_PATH="$HOME/Library/Developer/Toolchains/swift-${{ steps.resolve-version.outputs.version }}-RELEASE.xctoolchain/usr/bin"
        echo "Adding cached toolchain to PATH: $TOOLCHAIN_PATH"
        echo "$TOOLCHAIN_PATH" >> $GITHUB_PATH
